# Introduction to Numpy in Finance

Linear algebra library for manipulating arrays and matrics

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 1 NumPy Arrays

NumPy arrays will create an n-dimensional array#

$\text{n-dimensions:}$ $\begin{cases} \text{1-dimension} & \text{list} \\ \text{2-dimension} & \text{list of lists} \\ \text{3-dimension} & \text{list of lists of lists} \end{cases}$

## a. 1-Dimensional Array, i.e Vector

In [2]:
# Create a simple stock return list
stock_list = [3.5, 5, 2, 8, 4.2]

# Parse the list as a numpy array'

returns = np.array(stock_list)
returns

array([3.5, 5. , 2. , 8. , 4.2])

## b. 2-Dimensional Array, i.e. Matrix

In [4]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

## Changing Shape of Arrays

- Check the **shape** of the array: using the shape attribute of np.arrays() 

- **Reshape** the array specifying the appropriate number of row and column dimensions

In [8]:
# Check the shape
A.shape

(2, 2)

In [10]:
# Reshape the array
A.reshape(1,4)

array([[1, 2, 3, 4]])

## Indexing and Slicing Arrays

Same principle that applies to Python Lists

### 1-Dimensional Array

In [15]:
# Print first and last element of the returns array
print("first element: {}, last element: {}, elements in between: {}".format(
    returns[0], returns[len(returns) - 1], returns[1:3]))

first element: 3.5, last element: 4.2, elements in between: [5. 2.]


### 2-Dimensional Array (Matrix)

1. **Slicing with row and columns:**

`A[row element i : row element j, col element n : col element m]`

In [26]:
print("{}, first column: {}, first row: {}".format(
            A[:,:], A[:,0], A[0,:]))

[[1 2]
 [3 4]], first column: [1 3], first row: [1 2]


2. **Indexing Matrices by Rows:**

Inputting a single number in as the array argument returns the row indexed to the specified index in the argument

`A[row index]`

**Accessing elements** in the indexed row:

- Either by specifying the element in the index
- or by accessing it by adding another index

`A[row index, element in the row]`

`A[row index][element in the row]`

In [43]:
print("Entire row indexing: {}, \n access elements inside the index: {},\n access elements outside the index: {}"
      .format(A[1], A[1,1], A[1][1]))

Entire row indexing: [3 4], 
 access elements inside the index: 4,
 access elements outside the index: 4


## Array Functions

Most functions are applied to an array element-wise (as scalar-multiplication is).

In [44]:
print("log returns: {}, \n mean returns: {}, \n max return: {}".format(
            np.log(returns), np.mean(returns), np.max(returns)))

log returns: [1.25276297 1.60943791 0.69314718 2.07944154 1.43508453], 
 mean returns: 4.54, 
 max return: 8.0


**Scalars on arrays:**

In [48]:
returns*2 + 5

array([12. , 15. ,  9. , 21. , 13.4])

# Simulating a Universe of Stocks in NumPy

## Step 1: Create Empty Arrays to hold the assets and returns

We will need these arrays to build a portfolio

- Arrays are created with a fixed size and their dimensions cannot be changed without creating a new array

### NP.ZEROS ( )

Creates a NumPy array with the given dimension entirely filled in with $0$

**Vector:** Insert a single number

`np.zeros(number)`

<p style="text-align:center;">$\begin{bmatrix} 0 & 0 & 0 \end{bmatrix}$</p>

**Matrix:** Insert a tuple

`np.zeros((number rows, number columns))`

<p style="text-align:center;">$\begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}$</p>

In [53]:
asset_number = 10
assets = np.zeros((asset_number, 100))
returns = np.zeros((asset_number, 100))

## Step 2. Simulate a base asset (for cross-correlation)

We want the universe of stocks to be correlated with each other so we will use this initial value to generate the others

### Random Normal

`np.random.normal(mean, sd, N)`

$N$ is the number of draws we make

### Daily Returns and Current Prices

- **Daily Returns** are drawn from a random normal distrubution, i.e. daily *percentage* returns

- **Current Price** is obtained by taking the cumulative product of these samples

In [60]:
# Daily percentage returns
R_1 = np.random.normal(1.03, 0.03, 100)

# Make the first Asset returns equal to the daily percentage returns
returns[0] = R_1

# Make the first Asset price equal to the cumprod of its daily percentage returns
assets[0] = np.cumprod(R_1)